name: commit-tests
on:
    workflow_dispatch: { }
    push:
        branches: [ '**' ]
        tags-ignore: [ 'v**' ]
        paths-ignore: [ '**.md', 'api/mailinabox.yml' ]
jobs:
  # MiaB-LDAP using encryption-at-rest and connected to a remote Nextcloud
  remote-nextcloud-docker-ehdd:
    runs-on: ubuntu-22.04
    env:
      PRIMARY_HOSTNAME: box1.abc.com
      EHDD_KEYFILE: /tmp/keyfile
    steps:
      - uses: actions/checkout@v4
      - name: create ehdd keyfile
        run: sudo -E echo -n "secret" >/tmp/keyfile
      - name: setup
        run: sudo -E tests/system-setup/remote-nextcloud-docker.sh
      - name: test-runner
        run: sudo -E tests/runner.sh -dumpoutput -no-smtp-remote remote-nextcloud ehdd default
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: tests-output
          path: tests/out/**/screenshot.png
          if-no-files-found: ignore
          retention-days: 5

  # install upstream miab, then migrate to miabldap
  upgrade-from-upstream:
    runs-on: ubuntu-22.04
    env:
      PRIMARY_HOSTNAME: box2.abc.com
      # TODO: change UPSTREAM_TAG to 'main' once upstream is installable
      UPSTREAM_TAG: v67
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: sudo -E tests/system-setup/upgrade-from-upstream.sh --populate=basic --populate=totpuser
      - name: test-runner
        run: sudo -E tests/runner.sh -dumpoutput -no-smtp-remote upgrade-basic upgrade-totpuser default
