name: commit-tests
on: [workflow_dispatch]
jobs:
  # MiaB-LDAP connected to a remote Nextcloud
  remote-nextcloud-docker:
    runs-on: ubuntu-22.04
    env:
      PRIMARY_HOSTNAME: box1.abc.com
      FEATURE_MUNIN: false
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo -E tests/system-setup/remote-nextcloud-docker.sh upgrade basic
      - name: test-runner
        run: sudo -E tests/runner.sh -dumpoutput -no-smtp-remote default remote-nextcloud upgrade-basic


  # Upgrade from upstream install
  upgrade-from-upstream:
    runs-on: ubuntu-22.04
    env:
      PRIMARY_HOSTNAME: box2.abc.com
      UPSTREAM_TAG: main
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo -E tests/system-setup/upgrade-from-upstream.sh basic totpuser
      - name: test-runner
        run: sudo -E tests/runner.sh -dumpoutput -no-smtp-remote upgrade-basic upgrade-totpuser default

