name: commit-tests
on: [push]
jobs:
  # MiaB-LDAP connected to a remote Nextcloud
  remote-nextcloud-docker:
    runs-on: ubuntu-18.04
    env:
      PRIMARY_HOSTNAME: box1.abc.com
      FEATURE_MUNIN: false
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: tests/system-setup/remote-nextcloud-docker.sh upgrade basic
      - name: test-runner
        run: tests/runner.sh -dumpoutput -no-smtp-remote default remote-nextcloud upgrade-basic

